export const games =[
    {
        category:'main',
        tittle:'Hyperdimension Neptunia',
        cover:'/src/imgs/games/HDN.png',
        plataforms:[{
            type:'ps3',
            link:'#'
        }]
    },
    {
        category:'main',
        tittle:'Hyperdimension Neptunia MK2',
        cover:'/src/imgs/games/HDNMK2.png',
        plataforms:[{
            type:'ps3',
            link:'#'
        }]
    },
    {
        category:'main',
        tittle:'Hyperdimension Neptunia V Century',
        cover:'/src/imgs/games/HDNV.png',
        plataforms:[{
            type:'ps3',
            link:'#'
        }]
    },
    {
        category:'main',
        tittle:'Megadimension Neptunia VII',
        cover:'/src/imgs/games/HNRVII.png',
        plataforms:[{
            type:'ps4',
            link:'https://store.playstation.com/es-ar/product/UP0031-CUSA03133_00-GAME000000000000'
        },
        {
            type:'pc',
            link:'https://store.steampowered.com/app/460120/Megadimension_Neptunia_VII/'
        },
        {
            type:'nintendo',
            link:'https://www.nintendo.com/us/store/products/megadimension-neptunia-vii-switch/'
        }]
    },
    {
        category:'remake',
        tittle:'Hyperdimension Neptunia Re; Birth 1',
        cover:'/src/imgs/games/HNR1.png',
        plataforms:[{
            type:'vita',
            link:'https://neptunia.fandom.com/wiki/Hyperdimension_Neptunia_Re;Birth1'
        },
        {
            type:'pc',
            link:'https://store.steampowered.com/app/282900/Hyperdimension_Neptunia_ReBirth1/'
        }]
    },
    {
        category:'remake',
        tittle:'Hyperdimension Neptunia Re; Birth 2',
        cover:'/src/imgs/games/HNR2.png',
        plataforms:[{
            type:'vita',
            link:'https://neptunia.fandom.com/wiki/Hyperdimension_Neptunia_Re;Birth2_SISTERS_GENERATION'
        },
        {
            type:'pc',
            link:'https://store.steampowered.com/app/351710/Hyperdimension_Neptunia_ReBirth2_Sisters_Generation/'
        }]
    },
    {
        category:'remake',
        tittle:'Hyperdimension Neptunia Re; Birth 3',
        cover:'/src/imgs/games/HNR3.png',
        plataforms:[{
            type:'vita',
            link:'https://neptunia.fandom.com/wiki/Hyperdimension_Neptunia_Re;Birth3:_V_Generation'
        },
        {
            type:'pc',
            link:'https://store.steampowered.com/app/353270/Hyperdimension_Neptunia_ReBirth3_V_Generation/'
        }]
    },
    {
        category:'remake',
        tittle:'Megadimension Neptunia VIIR',
        cover:'/src/imgs/games/VIIR.jpg',
        plataforms:[{
            type:'ps4',
            link:'https://store.playstation.com/es-ar/product/UP0031-CUSA03133_00-GAME000000000000'
        },
        {
            type:'pc',
            link:'https://store.steampowered.com/app/460120/Megadimension_Neptunia_VII/'
        }]
    },
    {
        category:'remake',
        tittle:'Hyperdimension Neptunia Re:Verse',
        cover:'/src/imgs/games/RE_VERSE.png',
        plataforms:[{
            type:'ps5',
            link:'https://store.playstation.com/es-mx/product/UP0031-PPSA02721_00-NEPREVERSEGAME01'
        }]
    },
    {
        category:'spin-off',
        tittle:'Hyperdevotion Noire: Goddess Black Heart',
        cover:'/src/imgs/games/HNGB.png',
        plataforms:[{
            type:'vita',
            link:'https://en.wikipedia.org/wiki/Hyperdevotion_Noire:_Goddess_Black_Heart'
        },{
            type:'pc',
            link:'https://store.steampowered.com/app/415480/Hyperdevotion_Noire_Goddess_Black_Heart_Neptunia/'
        }]
    },
    {
        category:'spin-off',
        tittle:'Megatagmension + Neptune: Blanc VS Zombies',
        cover:'/src/imgs/games/MTNBNZ.png',
        plataforms:[{
            type:'vita',
            link:'https://neptunia.fandom.com/wiki/MegaTagmension_Blanc_%2B_Neptune_VS_Zombies'
        },{
            type:'pc',
            link:'https://store.steampowered.com/app/496810/MegaTagmension_Blanc__Neptune_VS_Zombies_Neptunia/'
        }]
    },
    {
        category:'spin-off',
        tittle:'Cyberdimension Neptunia: 4 Goddesses Online',
        cover:'/src/imgs/games/CYBERN.jpg',
        plataforms:[{
            type:'ps4',
            link:'https://store.playstation.com/es-mx/product/UP0031-CUSA07960_00-CYONMEGAMIONLINE'
        },{
            type:'pc',
            link:'https://store.steampowered.com/app/632350/Cyberdimension_Neptunia_4_Goddesses_Online/'
        }]
    },
    {
        category:'spin-off',
        tittle:'Superdimension Neptunia VS Sega Hard Girls',
        cover:'/src/imgs/games/SUPER.PNG',
        plataforms:[{
            type:'vita',
            link:'https://neptunia.fandom.com/wiki/Superdimension_Neptune_VS_Sega_Hard_Girls'
        },{
            type:'pc',
            link:'https://store.steampowered.com/app/571530/Superdimension_Neptune_VS_Sega_Hard_Girls/'
        }]
    },
    {
        category:'spin-off',
        tittle:'Hyperdimension Neptunia Producing Perfection',
        cover:'/src/imgs/games/PP.png',
        plataforms:[{
            type:'vita',
            link:'https://en.wikipedia.org/wiki/Hyperdimension_Neptunia:_Producing_Perfection'
        }]
    },
    {
        category:'spin-off',
        tittle:'Hyperdimension Neptunia U: Action Unleashed',
        cover:'/src/imgs/games/U_ACTION.png',
        plataforms:[{
            type:'vita',
            link:'https://en.wikipedia.org/wiki/Hyperdimension_Neptunia_U:_Action_Unleashed'
        },{
            type:'pc',
            link:'https://en.wikipedia.org/wiki/Hyperdimension_Neptunia_U:_Action_Unleashed'
        }]
    },
    {
        category:'spin-off',
        tittle:'Super Neptunia RPG',
        cover:'/src/imgs/games/RPG.png',
        plataforms:[{
            type:'play4',
            link:'https://store.playstation.com/es-mx/product/UP0031-CUSA12059_00-NEPTUNIA2D000001'
        },{
            type:'pc',
            link:'https://store.steampowered.com/app/1016960/Super_Neptunia_RPG/'
        },{
            type:'nintendo',
            link:'https://www.nintendo.com/us/store/products/super-neptunia-rpg-switch/'
        }]
    },
    {
        category:'spin-off',
        tittle:'Neptunia x SENRAN KAGURA: Ninja Wars',
        cover:'/src/imgs/games/NINJA.png',
        plataforms:[{
            type:'play4',
            link:'https://store.playstation.com/es-mx/product/UP0031-CUSA28812_00-SENRANNINJANEPUS'
        },{
            type:'pc',
            link:'https://store.steampowered.com/app/1836860/Neptunia_x_SENRAN_KAGURA_Ninja_Wars/'
        },{
            type:'nintendo',
            link:'https://www.nintendo.com/us/store/products/neptunia-x-senran-kagura-ninja-wars-switch/'
        }]
    },
    {
        category:'spin-off',
        tittle:'Neptunia: Sisters VS Sisters',
        cover:'/src/imgs/games/SISTERS.png',
        plataforms:[{
            type:'play4',
            link:'https://store.playstation.com/es-mx/product/UP0031-CUSA33705_00-NEPTUNIASISTERS1'
        },{
            type:'ps5',
            link:'https://store.playstation.com/es-mx/product/UP0031-PPSA07660_00-NEPTUNIASISTERS1'
        },{
            type:'pc',
            link:'https://store.steampowered.com/app/1932160/Neptunia_Sisters_VS_Sisters/'
        },{
            type:'nintendo',
            link:'https://www.nintendo.com/us/store/products/neptunia-sisters-vs-sisters-deluxe-bundle-switch/'
        },{
            type:'xbox',
            link:'https://www.xbox.com/en-us/games/store/neptunia-sisters-vs-sisters/9p88pkbbt41h'
        }]
    },
    {
        category:'spin-off',
        tittle:'Neptunia Game Maker R:Evolution',
        cover:'/src/imgs/games/MAKER.png',
        plataforms:[{
            type:'play4',
            link:'https://store.playstation.com/es-mx/concept/10007142'
        },{
            type:'pc',
            link:'#'
        },{
            type:'nintendo',
            link:'https://www.nintendo.com/us/store/products/neptunia-game-maker-r-evolution-digital-soundtrack-switch/'
        }]
    },
];